### ISSUE TITLE
报错 估计是少了登陆时候的同意用户协议

### ISSUE THREAD

**Issue by UMSR** [shibig666/QMYZ#2]
出错了 Expecting value: line 1 column 1 (char 0)
<!DOCTYPE html>

<html style="height: 100%">

    <head>

        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

        <title>用户授权 - 易班</title>

        <link rel="stylesheet" type="text/css" href="/oauth/css/2021/reset.css?v=20240809" />

        <link rel="stylesheet" type="text/css" href="/oauth/css/2021/authorization.css?v=20240809" />

    </head>

    <body onload="load_error();">

        <div class="w800">

            <div class="top_box">

                <div class="top_box_bg"></div>

                <div class="top_k">

                    <img src="http://img01.fs.yiban.cn/pic/8849493/web/thumb/open/14889439213270/8bln2644y9l2jocas8bhm25nmbjh0ssh.png" />

                    <ul class="top_k_r">

                        <li class="top_k_rt">青马易战</li>

                        <li class="top_k_rb">王岳俊(#74703702)</li>

                    </ul>

                </div>

            </div>

            <div class="center_box">

                <div class="center_t">

                                        <div class="center_t_tit">易班账号验证</div>

                    <div class="center_t_list"><var class="user"></var><input type="text" id="check_u" placeholder="请输入手机号"></div>

                    <div class="center_t_list"><var class="password"></var><input type="password" id="check_p" placeholder="请输入密码"></div>

                    <input type="test" id="key" value="-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCqG5Q3zoPM9ORiN2MOO4t8XUj
bsgYyEWSTvO+7R41KByTfq4gbyFIvHrrH/xREqxsrywp66022PfZidiFEPvcjFn6
MdgPOUzWJx5mIj7sEJAvQsV+yLT7iTuXg9FlGHy4Od4UWVaeyT/DhPZGTvTukCnU
xxcNRyE45CkZsuiDuQIDAQAB
-----END PUBLIC KEY-----
" style="display:none">

                                    </div>

                <div class="center_b">

                    <div class="center_b_tit">本应用由第三方服务商提供！</div>

                    <div class="center_b_tit">认可授权后应用将获得以下权限：</div>

                                        <div class="center_b_list">

                        <input type="checkbox" id="checkbox_1" name="table_cbox" class="table_cbox" value="1"checked="" disabled="" />

                        <label>获得你的用户信息、关系信息</label>

                    </div>

                                        <div class="center_b_list">

                        <input type="checkbox" id="checkbox_2" name="table_cbox" class="table_cbox" value="2"checked="" disabled="" />

                        <label>分享内容到你的消息通知</label>

                    </div>

                                        <div class="center_b_list">

                        <input type="checkbox" id="checkbox_3" name="table_cbox" class="table_cbox" value="3"checked="" disabled="" />

                        <label>获得你的动态、话题、评论</label>

                    </div>

                                        <div class="center_b_list">

                        <input type="checkbox" id="checkbox_4" name="table_cbox" class="table_cbox" value="4"checked="" disabled="" />

                        <label>获取你的实名信息、认证信息</label>

                    </div>

                                        <div class="center_b_list">

                        <input type="checkbox" id="checkbox_100" name="table_cbox" class="table_cbox" value="100" />

                        <label><b>同意<a href="javascript:;" class="click_alert" item="s0">《易班服务协议》</a>和<a href="javascript:;" class="click_alert" item="s1">《易班APP隐私保护指引》</a></b></label>

                    </div>

                                    </div>

            </div>

            <div class="bottom_box oauth_sure" sign="1">授权</div>

        </div>

        <script type="text/javascript" src="/global/js/jquery1.11.0.min.js?v=20240809"></script>

        <script type="text/javascript" src="/global/js/jsencrypt.min.js?v=20240809"></script>

        <script type="text/javascript" src="/global/js/sslcheck.js?v=20240809"></script>

        <script type="text/javascript" src="/oauth/js/2021/rem.js?v=20240809"></script>

        <script type="text/javascript" src="/oauth/js/2021/showText.js?v=20240809"></script>

        <script type="text/javascript" src="/oauth/js/2021/signDo.js?v=20240809"></script>

        <script type="text/javascript">

            var page_use = '237280cf3e2968bcdfe8f2ba9ecf6605d581fa68';

            var client_id = 'b3a31fa8019cc40b';

            var redirect_uri = 'http://f.yiban.cn/iapp76127';

            var state = '';

            function load_error() {

                            }

            $('.click_alert').click(function() {

                showItem = $(this).attr('item');

                switch(showItem) {

                                        case 's0':

                        showItem = '<p><b>欢迎您使用易班的服务！</b></p><p><b>为使用易班的服务，您应当阅读并遵守《易班服务协议》（以下简称“本协议”）。请您务必审慎阅读、充分理解各条款内容，特别是免除或者限制责任的条款，以及开通或使用某项服务的单独协议。限制、免责条款可能以黑体加粗形式提示您注意。</b></p><p>除非您已阅读并接受本协议所有条款，否则您无权使用易班提供的服务。您使用易班的服务即视为您已阅读并同意上述协议的约束。</p><p>易班有权在必要时修改本协议条款。您可以在相关服务页面查阅最新版本的协议条款。</p><p><b>本协议条款变更后，如果您继续使用易班提供的软件或服务，即视为您已接受修改后的协议。如果您不接受修改后的协议，应当停止使用易班提供的软

####省略一些

                        break;

                                        default:

                        showItem = '内容加载异常，请稍后再试。';

                        break;

                }

                showAlert({

                    title: $(this).html(), //弹出层提示文字

                    titColor:'#fff', //弹出层提示文字颜色

                    titbgColor:'#08A5EF', //弹出层提示背景

                    text: showItem, //【必填】，否则不能正常显示

                    btnText: '已阅', //按钮的文本

                    zindex: 5, //为了防止被其他控件遮盖，默认为2，背景的黑色遮盖层为1，修改后黑色遮盖层的z-index是这个数值的-1

                    color: '#fff', //按钮的文本颜色，默认白色

                    bgColor: '#08A5EF', //按钮的背景颜色，默认为#08A5EF

                    success: function() { //点击按钮后的回调函数

                        showToast({});

                    }

                });

            });

        </script>

    </body>

</html>

Traceback (most recent call last):
  File "C:\Users\umsrcdd\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\umsrcdd\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\umsrcdd\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\umsrcdd\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

**Comment by shibig666** [comment]
出现这个是因为缺少或者使用了失效的JSESSIONID导致的，这会重定向到易班的登录界面，你试试获取你自己最新的JSESSIONID
